### ISSUE TITLE
Possibility to support TODOs in block references?

### ISSUE THREAD

**Issue by lynoure** [8bitgentleman/Roam-Render-Components#1]
As I don't always get everything done in a day, I sometimes transfer TODOs of one day to another day. Copying over the block reference is my favorite way of doing that, but then they are not caught by the progress tracker. I could move them over, but then the historical perspective is lost.

Do you reckon it might be possible to get block reference TODOs included somehow? I'm a programmer, but new to both Clojure and hacking Roam.

**Comment by 8bitgentleman** [comment]
Oh interesting I had not considered that but you're totally right. Catching block ref'd todos would be very very useful. I'm new to clojure myself (within the last month) so it'll take me a bit to figure out the best way to go about that but happy to collaborate on it and answer any questions :)

Right now the component roughly

1. [pulls all of its children blocks](https://github.com/8bitgentleman/Roam-Render-Components/blob/7e0b43ee9d9b8b8571f13e59ed2eec68efb01f27/TODO%20Progress%20Bar/todo-progress-bar.cljs#L39) (their `:db/id` not `:block/uid`) 
2. [flattens them into a simple sequence](https://github.com/8bitgentleman/Roam-Render-Components/blob/7e0b43ee9d9b8b8571f13e59ed2eec68efb01f27/TODO%20Progress%20Bar/todo-progress-bar.cljs#L34)
3. [find how many times every page is referenced ](https://github.com/8bitgentleman/Roam-Render-Components/blob/7e0b43ee9d9b8b8571f13e59ed2eec68efb01f27/TODO%20Progress%20Bar/todo-progress-bar.cljs#L36)
4. [check the sequence for references to the `:db/id` for the TODO or DONE page](https://github.com/8bitgentleman/Roam-Render-Components/blob/7e0b43ee9d9b8b8571f13e59ed2eec68efb01f27/TODO%20Progress%20Bar/todo-progress-bar.cljs#L52)

My gut says block refs would have to be resolved between steps 1 and 2

**Comment by lynoure** [comment]
Without looking at them yet, it's possible that block references are a tricky beast. I know that for example {{word-count}} counts them as one each. 

Anyway, eager to collaborate any way I can.

**Comment by 8bitgentleman** [comment]
[The new v0.10](https://github.com/8bitgentleman/Roam-Render-Components/releases/tag/0.10) should solve this, give it a test and let me know!

**Comment by lynoure** [comment]
Sorry for taking such a long while to answer. Thank you for this!

It does the thing beautifully now. I've been reschuffling my Roam
workflows a bit, and I think I'll start integrating this. 

I used to have a podcast called How Do You To Do, about how people
manage the things they want to do, would you be open to being
interviewed for that, if I reboot it at some point?

**Comment by 8bitgentleman** [comment]
Ha that's a great title! Sure if you ever reboot it let me know, sounds fun.
