### ISSUE TITLE
Request: Disable DONE strikethrough in queries

### ISSUE THREAD

**Issue by karthajee** [8bitgentleman/Roam-Render-Components#3]
Hello,

There is awesome CSS in the TODO Progress Bar, which adds strikethrough decoration to the text. However, there is an issue when you use the DONE page inside a query. Strikethrough is applied on the full query result:

For e.g., this is an example of such a query in action
![image](https://user-images.githubusercontent.com/32452159/158244851-9ba359e7-d63e-4a92-b467-20218e5b77b6.png)

Is there any way to override this, when inside a query?

**Comment by 8bitgentleman** [comment]
Do you want no strikethrough at all when inside a query?

**Comment by 8bitgentleman** [comment]
You can try this if you only want `DONE` strokethrough inside a query

```

div.rm-block[data-page-links*="DONE"]:not(div.rm-block[data-page-links*="query"])>.rm-block-main{
  color:rgb(180,180,180);
   text-decoration: line-through;
}
```

**Comment by karthajee** [comment]
This is awesome, did the trick! Thanks again, Matt!
